name: SwornAnnouncer
main: com.squidfruit.swornannouncer.SwornAnnouncer
version: 2.0
description: >
             Sends The Strings In Config
commands:
    sareload:
       description: reloads config
             
permissions:
    swornannouncer.default:
        description: lets default players resive messages
        default: op
    swornannouncer.staff:
        description: lets staff players resive messages
        default: op
    swornannouncer.reload:
        description: lets player reload config
        default: op


