name: SwornAnnouncer
main: net.dmulloy2.swornannouncer.SwornAnnouncer
version: ${project.version}${project.build.number}
description: Group-based auto messaging plugin utilizing the action bar.
author: dmulloy2
softdepend: [ProtocolLib, Vault]
commands:
  am:
    description: SwornAnnouncer main command
    usage: /<command> <args>
    aliases: [swornannouncer, sa]
permissions:
  swornannouncer.cmd.send:
    description: Allows the use of /am send
    default: op
  swornannouncer.cmd.reload:
    description: Allows the use of /am reload
    default: op